import type { Product, Testimonial, Feature } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'High Protein Atta',
    description: 'Ancient wheat blend with 3x more protein. Perfect for rotis that fuel your day.',
    originalPrice: 1200,
    discountedPrice: 1164,
    discount: 3,
    rating: 4.8,
    reviewCount: 527,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&q=80',
    tag: 'Best Seller',
    category: 'Atta',
    weight: 'Pack of 3 × 1kg',
  },
  {
    id: '2',
    name: 'Khapli Atta',
    description: 'Heritage emmer wheat from native Indian farms. Low glycemic, high in nutrients.',
    originalPrice: 2200,
    discountedPrice: 1716,
    discount: 22,
    rating: 4.7,
    reviewCount: 314,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80',
    tag: 'Selling Fast',
    category: 'Atta',
    weight: '5kg + 5kg Combo',
  },
  {
    id: '3',
    name: 'A2 Desi Cow Ghee',
    description: 'Bilona-churned from native Gir cow milk. Rich in CLA, butyrate, and ancient goodness.',
    originalPrice: 14500,
    discountedPrice: 10100,
    discount: 30,
    rating: 4.9,
    reviewCount: 1038,
    image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=500&q=80',
    tag: 'Best Seller',
    category: 'Ghee',
    weight: '5L Dolchi',
  },
  {
    id: '4',
    name: 'Cold Pressed Mustard Oil',
    description: 'Wood-pressed kachi ghani mustard oil. Zero heat, maximum nutrition retained.',
    originalPrice: 2000,
    discountedPrice: 1880,
    discount: 6,
    rating: 4.8,
    reviewCount: 227,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80',
    tag: 'New Launch',
    category: 'Oils',
    weight: 'Pack of 5',
  },
  {
    id: '5',
    name: 'Ragi & Jowar Millet Mix',
    description: 'Ancient superfood blend of finger millet and sorghum. Naturally gluten-free.',
    originalPrice: 890,
    discountedPrice: 720,
    discount: 19,
    rating: 4.6,
    reviewCount: 183,
    image: 'https://images.unsplash.com/photo-1606787364406-a3cdf06c6d0c?w=500&q=80',
    tag: 'New Launch',
    category: 'Superfoods',
    weight: '1kg',
  },
  {
    id: '6',
    name: 'Cold Pressed Sesame Oil',
    description: 'Traditional til oil — a staple in Indian cooking for centuries. Rich and nutty.',
    originalPrice: 780,
    discountedPrice: 650,
    discount: 17,
    rating: 4.7,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=500&q=80',
    tag: 'Selling Fast',
    category: 'Oils',
    weight: '500ml',
  },
  {
    id: '7',
    name: 'Organic Sacha Inchi Protein',
    description: 'Complete plant protein from the Peruvian superfood. All 9 essential amino acids.',
    originalPrice: 1450,
    discountedPrice: 1190,
    discount: 18,
    rating: 4.5,
    reviewCount: 72,
    image: 'https://images.unsplash.com/photo-1611070786897-77a05b6bcc36?w=500&q=80',
    tag: 'New Launch',
    category: 'Superfoods',
    weight: '300g',
  },
  {
    id: '8',
    name: 'Pure Desi Ghee Combo',
    description: 'Family pack of A2 bilona ghee. Best value for daily cooking and Ayurvedic use.',
    originalPrice: 3600,
    discountedPrice: 2880,
    discount: 20,
    rating: 4.9,
    reviewCount: 445,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&q=80',
    tag: 'Best Seller',
    category: 'Combos',
    weight: 'Combo Pack',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Mumbai',
    rating: 5,
    review: "VedaRoots ghee has completely changed my cooking. You can actually taste the difference — it's rich, aromatic, and melts beautifully. My family notices it too.",
    product: 'A2 Desi Cow Ghee',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
  },
  {
    id: '2',
    name: 'Arjun Mehta',
    location: 'Bangalore',
    rating: 5,
    review: "As a fitness enthusiast, I was skeptical about protein atta. But the macros are real — and the rotis taste amazing. I've switched permanently.",
    product: 'High Protein Atta',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
  },
  {
    id: '3',
    name: 'Meera Nair',
    location: 'Kochi',
    rating: 5,
    review: "The cold-pressed oils smell and taste exactly like what my grandmother used to buy from the local mill. Pure nostalgia — and so much healthier.",
    product: 'Cold Pressed Sesame Oil',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
  },
  {
    id: '4',
    name: 'Rohit Gupta',
    location: 'Delhi',
    rating: 5,
    review: "I switched to Khapli Atta after my doctor recommended a low-GI diet. My sugar levels have stabilised and I honestly enjoy eating rotis again.",
    product: 'Khapli Atta',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
  },
  {
    id: '5',
    name: 'Ananya Krishnan',
    location: 'Chennai',
    rating: 5,
    review: "Fast delivery, beautiful packaging, and the quality is consistently excellent. VedaRoots is one of those rare brands that actually delivers on its promises.",
    product: 'Organic Millet Mix',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=100&q=80',
  },
];

export const features: Feature[] = [
  {
    id: '1',
    icon: '🌾',
    title: 'Native Sourcing',
    description: 'We source from native geographies across India — partnering with thousands of farmers who grow heritage varieties the traditional way.',
  },
  {
    id: '2',
    icon: '🏺',
    title: 'Traditional Processing',
    description: 'Bilona churning, cold-pressing, stone-milling. We process the way it was always done — slowly, without heat, without shortcuts.',
  },
  {
    id: '3',
    icon: '🔬',
    title: 'Extensive Quality Checks',
    description: 'Every batch goes through 20+ laboratory tests — heavy metals, pesticides, adulteration. You get only what passes the strictest standards.',
  },
  {
    id: '4',
    icon: '🏘️',
    title: 'Better Rural Lives',
    description: 'Every purchase directly empowers 5,000+ farming families across India — fair prices, long-term contracts, and a sustainable livelihood.',
  },
];

export const categories = [
  { id: 'All', label: 'All', emoji: '🛒' },
  { id: 'Ghee', label: 'Ghee', emoji: '🏺' },
  { id: 'Oils', label: 'Oils', emoji: '🫙' },
  { id: 'Atta', label: 'Atta', emoji: '🌾' },
  { id: 'Combos', label: 'Combos', emoji: '📦' },
  { id: 'Superfoods', label: 'Superfoods', emoji: '🌿' },
];

export const navLinks = [
  { href: '#products', label: 'Shop' },
  { href: '#why-us', label: 'Our Story' },
  { href: '#ingredients', label: 'Ingredients' },
  { href: '#testimonials', label: 'Reviews' },
];

export const featuredProduct = {
  name: 'A2 Desi Bilona Ghee',
  subtitle: 'The gold standard of purity',
  description:
    'Made from the milk of native Gir cows using the ancient bilona method — hand-churned curd, slow-simmered to golden perfection. No additives. No shortcuts.',
  benefits: [
    'Rich in fat-soluble vitamins A, D, E & K',
    'High in Conjugated Linoleic Acid (CLA)',
    'Supports gut health with butyrate',
    'Lactose & casein free',
    'Ayurvedically certified',
  ],
  originalPrice: 14500,
  discountedPrice: 10100,
  weight: '5L Dolchi',
  image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=800&q=85',
  ingredients: ['A2 Milk', 'Bilona Process', 'Gir Cow', 'Zero Additives'],
};
